"""canonical_baseline

Revision ID: 8dd23c0649ac
Revises: 
Create Date: 2026-06-12 14:09:16.535817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8dd23c0649ac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrador',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('nombre_usuario', sa.Text(), nullable=False),
    sa.Column('correo_electronico', sa.Text(), nullable=False),
    sa.Column('contrasena_hash', sa.Text(), nullable=False),
    sa.Column('rol', sa.Text(), nullable=False),
    sa.Column('fecha_ultimo_acceso', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerta',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('administrador_id', sa.Integer(), nullable=True),
    sa.Column('jugador_id', sa.Integer(), nullable=True),
    sa.Column('tipo_evento', sa.Text(), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('fecha_hora', sa.Date(), nullable=False),
    sa.Column('estado_lectura', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historialelo',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('enfrentamiento_id', sa.Integer(), nullable=False),
    sa.Column('jugador_id', sa.Integer(), nullable=False),
    sa.Column('valor_elo_anterior', sa.Integer(), nullable=False),
    sa.Column('valor_elo_actual', sa.Integer(), nullable=False),
    sa.Column('fecha_cambio', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jugador',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('nombre_usuario', sa.Text(), nullable=False),
    sa.Column('correo_electronico', sa.Text(), nullable=False),
    sa.Column('contrasena_hash', sa.Text(), nullable=False),
    sa.Column('rol', sa.Text(), nullable=False),
    sa.Column('fecha_ultimo_acceso', sa.Date(), nullable=False),
    sa.Column('elo_global', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('accion', sa.Text(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('descripcion_cambio', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['jugador.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournaments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('tipo_eliminacion', sa.Text(), nullable=False),
    sa.Column('rondas', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Text(), nullable=False),
    sa.Column('creador_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creador_id'], ['jugador.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('torneo_id', sa.Integer(), nullable=False),
    sa.Column('ronda', sa.Integer(), nullable=False),
    sa.Column('posicion', sa.Integer(), nullable=False),
    sa.Column('bracket_tipo', sa.Text(), nullable=False),
    sa.Column('jugador1_id', sa.Integer(), nullable=True),
    sa.Column('jugador2_id', sa.Integer(), nullable=True),
    sa.Column('ganador_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['ganador_id'], ['jugador.id'], ),
    sa.ForeignKeyConstraint(['jugador1_id'], ['jugador.id'], ),
    sa.ForeignKeyConstraint(['jugador2_id'], ['jugador.id'], ),
    sa.ForeignKeyConstraint(['torneo_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registrations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('torneo_id', sa.Integer(), nullable=False),
    sa.Column('jugador_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['jugador_id'], ['jugador.id'], ),
    sa.ForeignKeyConstraint(['torneo_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('torneo_id', 'jugador_id', name='uq_registration_torneo_jugador')
    )
    op.create_table('scheduled_matches',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('match_siguiente_id', sa.Integer(), nullable=True),
    sa.Column('estado_match', sa.Text(), nullable=False),
    sa.Column('marcador_detalle', sa.Text(), nullable=False),
    sa.Column('fecha_hora_programada', sa.Date(), nullable=False),
    sa.Column('resultado', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheduled_matches')
    op.drop_table('registrations')
    op.drop_table('matches')
    op.drop_table('tournaments')
    op.drop_table('audit_logs')
    op.drop_table('jugador')
    op.drop_table('historialelo')
    op.drop_table('alerta')
    op.drop_table('administrador')
    # ### end Alembic commands ###
